// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpravaPenezDeti.Data;

#nullable disable

namespace SpravaPenezDeti.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230516164135_SqlServerMigration")]
    partial class SqlServerMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiteUcet", b =>
                {
                    b.Property<int>("MajiteleId")
                        .HasColumnType("int");

                    b.Property<int>("UctyId")
                        .HasColumnType("int");

                    b.HasKey("MajiteleId", "UctyId");

                    b.HasIndex("UctyId");

                    b.ToTable("DiteUcet");
                });

            modelBuilder.Entity("SpravaPenezDeti.Models.Dite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CasVytoreni")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Jmeno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Deti");
                });

            modelBuilder.Entity("SpravaPenezDeti.Models.Pohyb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CasVytoreni")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Castka")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Detaily")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("JeOdchozi")
                        .HasColumnType("bit");

                    b.Property<int>("UcetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UcetId");

                    b.ToTable("Pohyby");
                });

            modelBuilder.Entity("SpravaPenezDeti.Models.Ucet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CasVytoreni")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("Jmeno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Zustatek")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id");

                    b.ToTable("Ucty");
                });

            modelBuilder.Entity("DiteUcet", b =>
                {
                    b.HasOne("SpravaPenezDeti.Models.Dite", null)
                        .WithMany()
                        .HasForeignKey("MajiteleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpravaPenezDeti.Models.Ucet", null)
                        .WithMany()
                        .HasForeignKey("UctyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpravaPenezDeti.Models.Pohyb", b =>
                {
                    b.HasOne("SpravaPenezDeti.Models.Ucet", "Ucet")
                        .WithMany("Pohyby")
                        .HasForeignKey("UcetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ucet");
                });

            modelBuilder.Entity("SpravaPenezDeti.Models.Ucet", b =>
                {
                    b.Navigation("Pohyby");
                });
#pragma warning restore 612, 618
        }
    }
}
